---
baseURL: "http://localhost"
languageCode: en-us
title: DevOpsDaysLA
theme: "PaperMod"

enableRobotsTXT: true

menu:
  main:
    - name: Registration
      url: "https://register.socallinuxexpo.org/"

markup:
  goldmark:
    renderer:
      unsafe: true
