---
baseURL: "http://localhost"
languageCode: en-us
title: DevOpsDaysLA
theme: "PaperMod"

enableRobotsTXT: true

menu:
  main:
    - name: Registration
      url: "https://register.socallinuxexpo.org/"
    - name: CFP
      url: "https://docs.google.com/forms/d/e/1FAIpQLSewxucXuZ5nmZYX-nBitrmnr1ZA-O7oc33kheNvoRw1ufEbgg/viewform"

markup:
  goldmark:
    renderer:
      unsafe: true
