---
defaultTheme: dark
disableThemeToggle: true
hideFooter: true
homeInfoParams:
    content: '---'

socialIcons:
  - name: "Discord"
    url: "https://discord.gg/WZRqsMC73f"
  - name: "LinkedIn"
    url: "https://www.linkedin.com/groups/13998392/"
  - name: "DevOpsDays"
    url: "https://devopsdays.org/events/2022-los-angeles/"
